//
// Created by rodion on 9/29/20.
//

#ifndef TODOLIST_SRC_CORE_PERSISTER_SERIALIZATIONERROR_H_
#define TODOLIST_SRC_CORE_PERSISTER_SERIALIZATIONERROR_H_

enum class SerializationError {
  NO_ERRORS,
  UNKNOWN_PATH,
  SERIALIZATION_ERROR,
  DESERIALIZATION_ERROR
};

#endif //TODOLIST_SRC_CORE_PERSISTER_SERIALIZATIONERROR_H_
