//
// Created by rodion on 9/20/20.
//

#ifndef TODOLIST_SRC_CLI_ERRORTYPE_H_
#define TODOLIST_SRC_CLI_ERRORTYPE_H_

enum class ErrorType {
  NO_ERRORS,
  INCORRECT_INPUT,
  OPERATION_ERROR,
  FATAL_ERROR
};

#endif //TODOLIST_SRC_CLI_ERRORTYPE_H_
