//
// Created by rodion on 9/27/20.
//

#ifndef TODOLIST_SRC_CORE_MEMORYMODEL_STORAGE_SERIALIZATION_SERIALIZERINTERFACE_H_
#define TODOLIST_SRC_CORE_MEMORYMODEL_STORAGE_SERIALIZATION_SERIALIZERINTERFACE_H_

class SerializerInterface {
 public:
  virtual void asdf() = 0;
};

#endif //TODOLIST_SRC_CORE_MEMORYMODEL_STORAGE_SERIALIZATION_SERIALIZERINTERFACE_H_
