//
// Created by rodion on 10/6/20.
//

#ifndef TODOLIST_SRC_CORE_API_OPERATIONRESULT_PERSISTERROR_H_
#define TODOLIST_SRC_CORE_API_OPERATIONRESULT_PERSISTERROR_H_

enum class PersistError {
  SERIALIZATION_ERROR,
  DESERIALIZATION_ERROR
};

#endif //TODOLIST_SRC_CORE_API_OPERATIONRESULT_PERSISTERROR_H_
